load("@rules_proto_grpc_python//:defs.bzl", "python_proto_library")
load("@protobuf//bazel:proto_library.bzl", "proto_library")

proto_library(
    name = "helloworld_proto",
    srcs = ["helloworld.proto"],
)

python_proto_library(
    name = "helloworld_python_proto",
    protos = [":helloworld_proto"],
)
