load("@rules_proto_grpc_python//:defs.bzl", "python_proto_library")
load("@protobuf//bazel:proto_library.bzl", "proto_library")

exports_files(["mypy.ini"])

proto_library(
    name = "helloworld_proto",
    srcs = ["helloworld.proto"],
)

python_proto_library(
    name = "helloworld_python_proto",
    # Generate .pyi files for the Python proto library.
    generate_pyi = True,
    protos = [":helloworld_proto"],
)

py_binary(
    name = "helloworld_example",
    srcs = ["helloworld_example.py"],
    deps = [":helloworld_python_proto"],
)
